### ISSUE TITLE
Feature: A colored blob is shown in the background

### ISSUE THREAD

**Issue by kasulk** [spreekaiser/art-gallery-app#39]
## Value proposition

As a user
I  can see a blob on the background
So that I get the impression, I'm actually looking at art

## Acceptance criteria

- [x] A colored blob is shown in the background
- [x] The blob is responsive

## Tasks

- [x] Find a free SVG
- [x] Implement the SVG into the project
- [x] Style the SVG properly
